const verbs = [
    { base: 'go', past: 'went', participle: 'gone' },
    { base: 'eat', past: 'ate', participle: 'eaten' },
    { base: 'run', past: 'ran', participle: 'run' },
    { base: 'like', past: 'liked', participle: 'liked' },
    { base: 'wish', past: 'wished', participle: 'wished' },
    { base: 'have', past: 'had', participle: 'had' },
    { base: 'get', past: 'got', participle: 'gotten' },
    { base: 'prefer', past: 'preferred', participle: 'preferred' },
    { base: 'sleep', past: 'slept', participle: 'slept' },
    { base: 'take', past: 'took', participle: 'taken' },
    { base: 'do', past: 'did', participle: 'done' },
    { base: 'meet', past: 'met', participle: 'met' },
    { base: 'cook', past: 'cooked', participle: 'cooked' },
    { base: 'believe', past: 'believed', participle: 'believed' },
    { base: 'know', past: 'knew', participle: 'known' },
    { base: 'learn', past: 'learned', participle: 'learned' },
    { base: 'work', past: 'worked', participle: 'worked' },
    { base: 'visit', past: 'visited', participle: 'visited' },
    { base: 'celebrate', past: 'celebrated', participle: 'celebrated' },
    { base: 'remember', past: 'remembered', participle: 'remembered' },
    { base: 'think', past: 'thought', participle: 'thought' },
    { base: 'educate', past: 'educated', participle: 'educated' },
    { base: 'attract', past: 'attracted', participle: 'attracted' },
    { base: 'react', past: 'reacted', participle: 'reacted' },
    { base: 'plan', past: 'planned', participle: 'planned' },
    { base: 'give', past: 'gave', participle: 'given' },
    { base: 'enter', past: 'entered', participle: 'entered' },
    { base: 'explore', past: 'explored', participle: 'explored' },
    { base: 'say', past: 'said', participle: 'said' },
    { base: 'write', past: 'wrote', participle: 'written' },
    { base: 'read', past: 'read', participle: 'read' },
    { base: 'see', past: 'saw', participle: 'seen' },
    { base: 'think', past: 'thought', participle: 'thought' },
    { base: 'feel', past: 'felt', participle: 'felt' },
    { base: 'understand', past: 'understood', participle: 'understood' },
    { base: 'become', past: 'became', participle: 'become' },
    { base: 'give', past: 'gave', participle: 'given' },
    { base: 'take', past: 'took', participle: 'taken' }
    // Add more verbs as needed
];

export default verbs;